name: Master Branch CI/CD

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check Out Repository
        uses: actions/checkout@v4
      -
        name: Docker Metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            scorya/distributed-workers
          tags: |
            type=ref,event=tag
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: linux-buildx-${{ github.sha }}
          restore-keys: |
            linux-buildx-
      -
        name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          platforms: linux/amd64,linux/arm64
          tags:  ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
